[build]
  # Définir le répertoire de base (où se trouve package.json)
  base = "la maison ibizienne boutique"

  # Définir la commande de construction (npm run build)
  command = "npm run build"

  # Définir le répertoire de publication (le dossier créé par la commande, qui est DANS le répertoire de base)
  publish = "dist"
